config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  namespace(:admin) do
    resources :downloads do
      collection { put "sort" }
    end
    resources :categories do
      collection { put "sort" }
      resources :topics do
        collection { put "sort" }
        resources :messages
      end
    end
    resources :topics do
      collection { put "sort" }
      resources :messages
    end
    resources :users do
      collection { put "sort" }
      resources :messages
    end
  end

  resources :documents, only: [:show]
  resources :images   , only: [:show]
  resources :assets   , only: [:show]
  resources :pages    , only: [:index, :show], as: :koi_pages
  root to: 'application#index'
  mount Koi::Engine => "/admin", as: "koi_engine"

  resources :categories, path: 'forum', only: [:index, :show] do
    resources :topics
  end
  resources :topic, path: 'topic' do
    resources :messages do
      get 'rate'
      get 'reply'
      get 'view_replies'
    end
  end
  resources :downloads , path: 'downloads' , only: [:index, :show]

  #must be at bottom
  get "/:id"  => "pages#show", as: :page
end

app/models/message.rb
class Message < ActiveRecord::Base

  has_crud

  belongs_to :topic
  belongs_to :user
  belongs_to :message

  has_many   :messages, dependent: :destroy
  scope :replies, -> (message) { where(message: message) }

  validates_presence_of :content
  validates_length_of :content, :minimum => 2
  validates_length_of :content, :maximum => 500

  crud.config do
    fields  content: { type: :rich_text },
            topic_id: { type: :topic}
    config :admin do
      actions only:  [:index, :show, :new, :edit]
      index fields: [:topic_id, :content],
            order:  { created_at: :desc }
      form  fields: [ :content]
      csv   fields: [ :content]
    end
  end

  def is_reply?
    message
  end
end

app/controllers/admin/messages_controller.rb
class Admin::MessagesController < Koi::AdminCrudController
end

app/controllers/messages_controller.rb
class MessagesController < CrudController

  belongs_to :topic

  def create
    @topic    = parent
    @reply  = parent.messages.build(permitted_params[:message])
    @message = @reply.message
    if user_signed_in?
      @reply.user = current_user
    end
    respond_to do |format|
      if @reply.save
        @messages = parent.messages.replies(@reply.message).sort{|a,b| a.created_at <=> b.created_at}
        format.html { redirect_to @reply.post, notice: 'Message sent' }
        format.js   { }
        format.json { render :show, status: :created, location: @reply }
      else
        format.html { render :new }
        format.js   { }
        format.json { render json: @reply.errors, status: :unprocessable_entity}
      end
    end
  end

  def rate
    @topic    = parent
    @reply  = parent.messages.find(params[:message_id])
    @messages = parent.messages
    unless cookies[@reply.id.to_s] == "liked"
      cookies[@reply.id.to_s] = "liked"
      @reply.rating += 1
      respond_to do |format|
        if @reply.save
          format.js { }
        end
      end
    end
  end

  def reply
    @topic    = parent
    @reply  = Message.new(topic_id: @topic.id)
    @message =  parent.messages.find(params[:message_id])
    @reply.message = @message
    respond_to do |format|
      format.js { }
    end
  end

  def view_replies
    @topic    = parent
    @message  = parent.messages.find(params[:message_id])
    @messages = parent.messages.replies(@message).sort{|a,b| a.created_at <=> b.created_at}
    respond_to do |format|
      format.js { }
    end
  end

private

  def permitted_params
    params.permit(message: [ :content, :message_id], time: [ :last_updated])
  end

  def valid?(message, reply)
    true #message && reply && message.topic_id == reply.topic_id
  end

end

app/helpers/message_helper.rb
module MessageHelper

  def liked(message)
    cookies[message.id.to_s] == "liked"
  end
end

app/views/messages/_form.html.erb
<%= simple_form_for [@topic,@reply], remote: true do |f| %>
  <%= f.error_notification %>
  <div class="inputs">
    <%= f.input :content , label: "Message" %>
    <% if @reply.message %>
      <%= f.input :message_id, as: :hidden, value: @reply.message_id %>
    <% end %>
  </div>
  <div class="actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/messages/_message.html.erb
<tr>
  <td>
    <div message="<%= @reply.id %>">
      <small>
        <b><%= get_username(@reply) %></b> on <%= get_date(@reply) %>
      </small>
      <p><%= @reply.content %></p>
      <span like="<%= @reply.id %>">
        <%= @reply.rating %>
        <% if liked(@reply) %>
          <small>Liked</small>
        <% else %>
          <%= link_to "Like" , topic_message_rate_path( @topic, @reply), remote: true %>
        <% end %>
      </span>
      <%= link_to "Reply", topic_message_reply_path(@topic, @reply), remote: true %>
      <span reply="<%= @reply.id %>" reply>
      </span>
      <div>
        <table id="reply" replies="<%= @reply.id %>">
          <%= link_to "View replies", topic_message_view_replies_path(@topic, @reply), remote: true %>
        </table>
      </div>
    </div>
  </td>
</tr>

app/views/messages/create.js.erb
console.log("create.js.erb file");
<% if @reply.persisted? %>
  <% if @reply.is_reply? %>
    $("[reply]").html("");
    $("[replies='<%= escape_javascript(@message.id.to_s)%>']").html(" ");
    <% @messages.each do |message| %>
        <%@reply = message%>
        $("[replies='<%= escape_javascript(@message.id.to_s)%>']")
        .append("<%= escape_javascript(render 'messages/message')%>");
    <% end %>
  <% else %>
    $("[data-forum]").append("<%= escape_javascript(render 'messages/message')%>");
  <% end %>
  <% @reply = Message.new(topic_id: @topic.id) %>
  $("[message-form]").html("<%= escape_javascript(render 'messages/form')%>");
<% else %>
  <% if @reply.is_reply? %>
    $("[reply]").html("");
    $("[reply='<%= escape_javascript(@message.id.to_s)%>']")
      .html("<%= escape_javascript(render 'messages/form')%>");
  <% end %>
<% end %>

app/views/messages/rate.js.erb
console.log("rate.js.erb file");

$("[like='<%= escape_javascript(@reply.id.to_s)%>']").html("<%= @reply.rating%> Liked");

app/views/messages/reply.js.erb
console.log("reply.js.erb file");
$("[reply]").html("");
$("[reply='<%= escape_javascript(@message.id.to_s)%>']")
  .html("<%= escape_javascript(render 'messages/form')%>");

app/views/messages/view_replies.js.erb
console.log("view_reply.js.erb file");
$("[replies='<%= escape_javascript(@message.id.to_s)%>']").html(" ");
<% @messages.each do |message| %>
    <%@reply = message%>
    $("[replies='<%= escape_javascript(@message.id.to_s)%>']")
    .append("<%= escape_javascript(render 'messages/message')%>");
<% end %>