config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  namespace(:admin) do
    resources :downloads do
      collection { put "sort" }
    end
    resources :categories do
      collection { put "sort" }
      resources :topics do
        collection { put "sort" }
        resources :messages
      end
    end
    resources :topics do
      collection { put "sort" }
      resources :messages
    end
    resources :users do
      collection { put "sort" }
      resources :messages
    end
  end

  resources :documents, only: [:show]
  resources :images   , only: [:show]
  resources :assets   , only: [:show]
  resources :pages    , only: [:index, :show], as: :koi_pages
  root to: 'application#index'
  mount Koi::Engine => "/admin", as: "koi_engine"

  resources :categories, path: 'forum', only: [:index, :show] do
    resources :topics
  end
  resources :topic, path: 'topic' do
    resources :messages do
      get 'rate'
      get 'reply'
      get 'view_replies'
    end
  end
  resources :downloads , path: 'downloads' , only: [:index, :show]

  #must be at bottom
  get "/:id"  => "pages#show", as: :page
end

app/models/topic.rb
class Topic < ActiveRecord::Base

  has_crud
  belongs_to :category
  has_many :messages, dependent: :destroy

  crud.config do
    fields   title:   { type: :default },
             content: { type: :rich_text }

    config :admin do
      actions only:  [:index, :show, :new, :edit]
      index fields: [:title, :content],
            relations: [:messages],
            order:  { created_at: :desc }
      form  fields: [:title, :content]
      csv   fields: [:title, :content]
    end
  end
end

app/controllers/admin/topics_controller.rb
class Admin::TopicsController < Koi::AdminCrudController
end

app/controllers/topics_controller.rb
class TopicsController < CrudController

  belongs_to :category

  private

  def permitted_params
    params.permit(topic: [:creator, :title, :content])
  end

end

app/views/topics/_form.html.erb
<%= simple_form_for [@category, @topic]   do |f| %>
  <%= f.error_notification %>

  <div class="inputs">
    <%= f.input :creator %>
    <%= f.input :title %>
    <%= f.input :content %>
  </div>

  <div class="actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/topics/edit.html.erb
<% content_for :title, "Edit Topic" %>

<%= render "form" %>

<p>
  <%= link_to "Show", category_topic_path(@category, @topic) %> |
  <%= link_to "View All", category_topics_path(@category) %>
</p>

app/views/topics/index.html.erb
<% content_for :title, "Topics" %>

<table id="forum">
  <tr>
    <th>Creator</th>
    <th>Title</th>
    <th>Content</th>
  </tr>
  <% @topics.each do |topic| %>
    <tr>
      <td><%= topic.creator %></td>
      <td><%= topic.title %></td>
      <td><%= topic.content %></td>
      <td><%= link_to "Show", category_topic_path(@category,topic) %></td>
      <td><%= link_to "Edit", edit_category_topic_path(@category,topic) %></td>
      <td><%= link_to "Destroy", category_topic_path(@category,topic), method: :delete, data: {confirm: 'Are you sure?'}%></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Topic", new_category_topic_path(@category) %></p>

app/views/topics/new.html.erb
<% content_for :title, "New Topic" %>

<%= render "form" %>

<p><%= link_to "Back to list", category_topics_path(@category) %></p>

app/views/topics/show.html.erb
<% content_for :title, "Topic" %>

<table id="forum">
  <tr>
    <th>
      <%= @topic.title %>
    </th>
  </tr>
  <tr>
    <td>
      <p><%= @topic.content %></p>
      <small>
        <%= get_date(@topic) %>
      </small>
    </td>
  </tr>
</table>

<table id="forum" data-forum>
  <tr>
    <th>
      Comments
    </th>
  </tr>
  <% @topic.messages.sort{|a,b| a.created_at <=> b.created_at}.each do |message| %>
    <% unless message.is_reply? %>
      <%@reply = message%>
      <%= render 'messages/message'%>
    <% end %>
  <% end %>
</table>

<table id="forum">
  <tr>
    <th>
      <p>
        Comment as <%= username %>
        <br>
        <div message-form>
          <% @reply = Message.new(topic_id: @topic.id) %>
          <%= render 'messages/form' %>
        </div>
      </p>
    </th>
  </tr>
</table>