config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  namespace(:admin) do
    resources :downloads do
      collection { put "sort" }
    end
    resources :categories do
      collection { put "sort" }
      resources :topics do
        collection { put "sort" }
        resources :messages
      end
    end
    resources :topics do
      collection { put "sort" }
      resources :messages
    end
    resources :users do
      collection { put "sort" }
      resources :messages
    end
  end

  resources :documents, only: [:show]
  resources :images   , only: [:show]
  resources :assets   , only: [:show]
  resources :pages    , only: [:index, :show], as: :koi_pages
  root to: 'application#index'
  mount Koi::Engine => "/admin", as: "koi_engine"

  resources :categories, path: 'forum', only: [:index, :show] do
    resources :topics
  end
  resources :topic, path: 'topic' do
    resources :messages do
      get 'rate'
      get 'reply'
      get 'view_replies'
    end
  end
  resources :downloads , path: 'downloads' , only: [:index, :show]

  #must be at bottom
  get "/:id"  => "pages#show", as: :page
end

app/models/category.rb
class Category < ActiveRecord::Base

  has_crud :orderable => true
  has_many :topics, dependent: :destroy

  crud.config do
    fields   title:   { type: :default },
             content: { type: :rich_text }

    config :admin do
      actions only:  [:index, :show, :new, :edit]
      index fields: [:title, :content],
            relations: [:topics],
            order:  { created_at: :desc }
      form  fields: [:title, :content]
      csv   fields: [:title, :content]
    end
  end

  def to_s
    title || "New category"
  end

end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Koi::AdminCrudController
end

app/controllers/categories_controller.rb
class CategoriesController < CrudController

  def index
    @categories = Category.ordered
  end

end

app/views/categories/index.html.erb
<% content_for :title, "Categories" %>

<table id="forum">
  <tr>
    <th>Title</th>
  </tr>
  <% @categories.each do |category| %>
    <tr>
      <td>
        <b><%= link_to category.title, category_topics_path(category) %></b>
        <p><%= category.content.html_safe %></p>
      </td>
    </tr>
  <% end %>
</table>

app/views/categories/show.html.erb
<% content_for :title, "Category" %>

<p>
  <strong>Title:</strong>
  <%= @category.title %>
</p>
<p>
  <strong>Content:</strong>
  <%= @category.content.html_safe %>
</p>

<table id="forum">
  <tr>
    <th>
      Topics
      <br><%= link_to "Create new Topic", new_category_topic_path(@category) %>
    </th>
  </tr>
  <% @category.topics.each do |topic| %>
    <tr>
      <td>
        <b><%= topic.title%></b>
        <b><%= link_to "Show topic", topics_path(topic) %></b>
        <p><%= topic.content.html_safe %></p>
      </td>
    </tr>
  <% end %>
</table>
<p>
  <%= link_to "View All", categories_path %>
</p>